[build]
  command = "npm install -g pnpm && pnpm install && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION = "false"
  PNPM_VERSION = "8"

[[plugins]]
  package = "@netlify/plugin-nextjs"
