[build]
  command = "npm install -g pnpm@8 && pnpm install --no-frozen-lockfile && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
